### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-abbey#6]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] donation_mass - By @alexis-via - #8 
- [x] donation_stay - By @alexis-via - #8 
- [x] mass - By @alexis-via - #8 
- [x] stay - By @alexis-via - #8
